### ISSUE TITLE
Better naming

### ISSUE THREAD

**Issue by youssefbm** [Douaa19/Douaa-Larif#1]
pour le nom du repo, au lieu de maquettage mettez maquettage_loopstudios
pout les noms des fichiers, merci faire un nommage plus claire

**Comment by Douaa19** [comment]
Bien reçu monsieu

Le ven. 22 janv. 2021 à 22:24, YoussefOuadid <notifications@github.com> a
écrit :

**Comment by youssefbm** [comment]
Bravo, très bonne réactivité. Continue comme ça.

**Comment by Douaa19** [comment]
Merci monsieur

Le ven. 22 janv. 2021 à 22:28, YoussefOuadid <notifications@github.com> a
écrit :
